//
var data = {
	x: obj_Global.GUI_WIDTH * .5,
	y: obj_Global.GUI_HEIGHT * .5,
	width: 360,
	height: 260,
	fillColor: c_ltgray,
	fillAlpha: .5,
	radius: 20,
	grid: "column",
	children: [
		{
			margin: 20,
			padding: 20,
			fillColor: c_modern_black,
			fillAlpha: .5,
			flow: "split",
			grid: "column",
			children: [
				{
					grid: "row",
					flow: "split",
					fillColor: c_green,
					fillAlpha: .5,
					children: [
						{
							margin: 10,
							padding: 10,
							fillColor: c_orange,
							fillAlpha: .5,
							hAlign: fa_left,
							vAlign: fa_top,
							str: "Top Left",
						},
						{
							margin: 10,
							padding: 10,
							fillColor: c_orange,
							fillAlpha: .5,
							hAlign: fa_center,
							vAlign: fa_top,
							str: "Top Middle",	
						},
						{
							margin: 10,
							padding: 10,
							fillColor: c_orange,
							fillAlpha: .5,
							hAlign: fa_right,
							vAlign: fa_top,
							str: "Top Right",
						},
					],
				},
				{
					grid: "row",
					flow: "split",
					fillColor: c_blue,
					fillAlpha: .5,
					children: [
						{
							margin: 10,
							padding: 10,
							fillColor: c_purple,
							fillAlpha: .5,
							hAlign: fa_left,
							vAlign: fa_middle,
							str: "Middle Left",
						},
						{
							margin: 10,
							padding: 10,
							fillColor: c_purple,
							fillAlpha: .5,
							hAlign: fa_center,
							vAlign: fa_middle,
							str: "Middle Middle",
						},
						{
							margin: 10,
							padding: 10,
							fillColor: c_purple,
							fillAlpha: .5,
							hAlign: fa_right,
							vAlign: fa_middle,
							str: "Middle Right",
						},
					],
				},
				{
					grid: "row",
					flow: "split",
					fillColor: c_red,
					fillAlpha: .5,
					children: [
						{
							margin: 10,
							padding: 10,
							fillColor: c_olive,
							fillAlpha: .5,
							hAlign: fa_left,
							vAlign: fa_bottom,
							str: "Bottom Left",
						},
						{
							margin: 10,
							padding: 10,
							fillColor: c_olive,
							fillAlpha: .5,
							hAlign: fa_center,
							vAlign: fa_bottom,
							str: "Bottom Middle",
						},
						{
							margin: 10,
							padding: 10,
							fillColor: c_olive,
							fillAlpha: .5,
							hAlign: fa_right,
							vAlign: fa_bottom,
							str: "Bottom Right",
						},
					],
				},
			],
		},
	],
};			

draw_container(data);
//